# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 00:03
from __future__ import unicode_literals

import community.groups.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=community.groups.models.get_group_image_path)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_image', to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_created=True, verbose_name='last activity')),
                ('join_date', models.DateTimeField(auto_created=True, verbose_name='date joined')),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_group_image', to='groups.GroupImage'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together=set([('user', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupimage',
            unique_together=set([('group', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('community', 'id')]),
        ),
    ]
