# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 21:42
from __future__ import unicode_literals

import community.groups.models
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=community.groups.models.get_group_image_path)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_image', to='groups.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_group_image', to='groups.GroupImage'),
        ),
        migrations.AlterUniqueTogether(
            name='groupimage',
            unique_together=set([('group', 'id')]),
        ),
    ]
