# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20170214_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='community',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together=set([('user', 'group')]),
        ),
    ]
