# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20161205_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
