# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 21:14
from __future__ import unicode_literals

import community.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161106_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/accounts/profiles/default.jpg', upload_to=community.accounts.models.get_profile_image_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_profile_image', to='accounts.ProfileImage'),
        ),
        migrations.AlterUniqueTogether(
            name='profileimage',
            unique_together=set([('profile', 'id')]),
        ),
    ]
