# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:00
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161113_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=annoying.fields.AutoOneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_profile_image', to='accounts.ProfileImage'),
        ),
    ]
