# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:52
from __future__ import unicode_literals

import community.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='accounts.ProfileImage'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to=community.accounts.models.get_profile_image_path),
        ),
    ]
