# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:04
from __future__ import unicode_literals

import community.accounts.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161129_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=community.accounts.models.get_profile_image_path),
        ),
    ]
