# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_time', models.DateTimeField(auto_created=True, verbose_name='date joined')),
                ('status', models.CharField(choices=[('GOING', 'going'), ('PROBABLY', 'probably'), ('MIGHT', 'might'), ('NOT_GOING', 'not going')], default='GOING', max_length=200)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('duration', models.IntegerField(default=2, verbose_name='duration (hours)')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='meetups.Meetup'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together=set([('community', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set([('user', 'meetup')]),
        ),
    ]
