# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupattendee',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetupattendee',
            name='signup_time',
            field=models.DateTimeField(auto_created=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='meetupattendee',
            name='status',
            field=models.CharField(choices=[('GOING', 'going'), ('PROBABLY', 'probably'), ('MIGHT', 'might'), ('NOT_GOING', 'not going')], default='GOING', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='meetupattendee',
            unique_together=set([('user', 'meetup')]),
        ),
    ]
