# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20161107_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='duration (hours)'),
        ),
    ]
