# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20170221_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
