# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetup_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
