# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetupAttendee',
            new_name='Attendee',
        ),
    ]
