# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20161106_2234'),
        ('meetups', '0005_auto_20161107_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='meetups.Meetup'),
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together=set([('community', 'id')]),
        ),
    ]
