# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20161107_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='created_date',
            field=models.DateTimeField(auto_created=True, verbose_name='date created'),
        ),
    ]
