# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
