# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_communityuserprofile_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
    ]
