# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20161106_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='location',
        ),
    ]
