# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
