# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20161106_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
