# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20161106_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
