# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='date created')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('private', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_time', models.DateTimeField(auto_created=True, verbose_name='date joined')),
                ('status', models.CharField(choices=[('GOING', 'going'), ('PROBABLY', 'probably'), ('MIGHT', 'might'), ('NOT_GOING', 'not going')], default='GOING', max_length=200)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='last updated')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendee', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together=set([('user', 'event')]),
        ),
    ]
