# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='event',
            name='lastname',
            field=models.CharField(default='shayan', max_length=200),
            preserve_default=False,
        ),
    ]
