# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='status',
            field=models.CharField(choices=[('GOING', 'going'), ('INTERESTED', 'interested'), ('NOT_GOING', 'not going')], default='GOING', max_length=200),
        ),
    ]
